config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  #ressources pour les produits dans le panier
  resources :line_items

  #resources pours les paniers
  resources :carts, only: [:new, :create, :destroy, :show]

  #resources pour les produits
  resources :products

  #resources for admin
  resources :admin, only: [:new, :create, :destroy]

  #resources for user_session
  resources :session

  #creationuser
  resources :user do
  	resources :message , only: [ :new , :index , :destroy , :create , :edit , :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product, currentuser)
    item = line_items.find_by(product: product, current_user_id: currentuser)

    if item
      item.quantity += 1
    else
      item = line_items.new(product: product, current_user_id: currentuser)
    end
    item
  end
  
  def total
    line_items.to_a.sum(&:total)
  end
end

app/models/checkout.rb
class Checkout < ApplicationRecord
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  def total
    product.price * quantity
  end

end

app/models/message.rb
class Message < ApplicationRecord
	validates :contenu, presence: true
	belongs_to :user
end

app/models/payer.rb
class Payer < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items, dependent: :nullify
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	has_many :messages
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def new; end

  def create
     admin_input_email = params[:email]
     admin_input_password = params[:password]

    puts admin = Admin.find_by(email: admin_input_email)

    if admin && admin.authenticate(admin_input_password)
      # puts "tafiditra"
      session[:admin_id] = admin.id
      redirect_to products_path

    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session.delete(:admin_id)
    redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_product, only: [:show]

  # GET /products
  # GET /products.json
  def index
    # @products = Product.order(:title)
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :image_url)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
 
  def new
  end

  def create

  	puts '*' * 100

  	User.create(nom: params[:Nom] , prenom: params[:Prenom] , age: params[:Age] , email: params[:Email] , password: params[:password])
  	
  end
end

app/helpers/admin_helper.rb
module AdminHelper
  def current_admin
    Admin.find_by(id: session[:admin_id])
 end

  def log_in(admin)
    session[:admin_id] = admin.id
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/page_helper.rb
module PageHelper

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/session_helper.rb
module SessionHelper

  def current_user
    User.find_by(id: session[:id])
  end

  def log_in(user)
   session[:user_id] = user.id
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title></title>

    <link rel="stylesheet" type="text/css" href="/css/acceuil.css">

  </head>

  <body class="bod">
      <nav class="navbar navbar-expand-md bg-dark navbar-dark">

      <p class="logo">
        Sayna<span class="spa">Hub</span>
      </p>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="collapsibleNavbar">

        <ul class="navbar-nav">

          <li class="nav-item">
            <a class="nav-link" href="#">Acceuil</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="#/message">Forum</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="<%=new_admin_path%>">Admin</a>
          </li>

          <li class="nav-item">
            <% if(current_user) %>
              <!-- <a class="nav-link" href="/session/<""%= @id %>" data-method="delete" >Log Out</a> -->
              <%= link_to "Log Out", session_path(current_user.id), method: :delete, class: 'nav-link' %>

            <%else%>
             <a class="nav-link" href=<%= new_session_path %>>Log In</a>
            <%end%>
          </li>

        </ul>

      </div>

    </nav>

    <!-- carousel -->

    <div>

      <div id="demo" class="carousel slide" data-ride="carousel">

        <!-- Indicators -->
        <ul class="carousel-indicators">
          <li data-target="#demo" data-slide-to="0" class="active"></li>
          <li data-target="#demo" data-slide-to="1"></li>
          <li data-target="#demo" data-slide-to="2"></li>
        </ul>

        <!-- The slideshow -->
        <div class="carousel-inner">

          <div class="carousel-item active">
            <img src="/sary/g.jpg" alt="Los Angeles" width="1400px" height="480px">
          </div>

          <div class="carousel-item">
            <img src="sary/a.jpg" alt="Chicago" width="1400px" height="480px">
          </div>

          <div class="carousel-item">
            <img src="sary/f.jpg" alt="New York" width="1400px" height="480px">
          </div>
        </div>

        <!-- Left and right controls -->
        <a class="carousel-control-prev" href="#demo" data-slide="prev">
          <span class="carousel-control-prev-icon"></span>
        </a>
        <a class="carousel-control-next" href="#demo" data-slide="next">
          <span class="carousel-control-next-icon"></span>
        </a>
      </div>

    </div>

    <!-- grid -->
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Sary</th>
          <th>Karazany</th>
          <th>Mombamonba le saka belouha</th>
          <th>Vidiny</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>

          <% @products.each do |product| %>

              <tr>
                <td><%= image_tag product.image_url, width: 250 %></td>
                <!-- -->
                <td><%= product.title %></td>
                <!--truncate=> avec la parametre length permet de couper un text; strip_tags=>supprime ts les balises html de la chaine -->
                <td><%= truncate strip_tags(product.description), length: 250 %></td>
                <!--number_to_currency: pr avoir unité, format: "%n/u" : n=>nombre puis unité-->
                <td><%= number_to_currency product.price, unit: "MGA ", separator: ",", format: "%u%n" %></td>
                <!-- image_tag => recu de l'image dans app/assets/images -->
                <!-- <td> <''%= link_to 'Show', catalog_url(product), class: "btn btn-primary" %></td> -->
                <!-- lien d'ajout au panier -->
                <!-- <td><''%= button_to 'Ajouter au panier', line_items_path(product_id: product), class: "btn btn-primary" %></td> -->
                <% if(current_user) %>
                    <td><%= button_to 'Ajouter au panier', line_items_path(product_id: product), class: "btn btn-primary" %></td>
                  <%else%>
                    <td><%= link_to 'Ajouter au panier', new_session_path, class: "btn btn-primary" %></td>
                <%end%>
              </tr>
            <% end %>

      </tbody>
    </table>
  </body>
</html>

<%if current_user%>
  <%= current_user.id%>
  <%else%>
  <p>no user</p>
<%end%>